// Content model for The Mindful Engineer
// Post types: essay | note | link | snippet

window.SITE = {
  name: "The Mindful Engineer",
  domain: "mindful.engineer",
  author: "Benjamin Kitt",
  tagline: "Moving fast, on purpose. Writing about software, change, and the people in the middle of it.",
  bio: "I ship fast and think carefully about who's along for the ride. This is where I work out what I think — in long articles, short notes, and the occasional code fragment.",
  nav: [
    { label: "Index", href: "#/" },
    { label: "Articles", href: "#/essays" },
    { label: "Notes", href: "#/notes" },
    { label: "Archive", href: "#/archive" },
    { label: "About", href: "#/about" },
    { label: "Now", href: "#/now" },
  ],
};

window.POSTS = [
  {
    id: "fast-and-present",
    type: "essay",
    title: "Fast and Present Are Not Opposites",
    subtitle: "On shipping quickly without leaving anyone behind.",
    date: "2026-04-12",
    readMin: 7,
    tags: ["practice", "teams"],
    featured: true,
    excerpt: "Mindful engineering is not slow engineering. It is fast engineering done with both eyes open — to the work, and to the people doing it.",
    body: [
      { k: "p", t: "There is a version of \"mindful engineering\" I want to reject on sight. It is the one that implies we should slow down, take a breath, write fewer lines, ship less often. I have seen teams adopt it and grow worse — not kinder, not more humane, just slower, with all the same politics." },
      { k: "p", t: "The best engineers I know ship constantly. They merge multiple times a day. They rewrite things on Fridays. They treat velocity as a form of respect for the problem. What makes them mindful is not their pace. It is that they are awake to the choices they are making at that pace." },
      { k: "h2", t: "Speed is the easy part" },
      { k: "p", t: "If you have been doing this for long enough, you can go fast. Modern tools will carry you a stunning distance. An intern with good taste and a good model can ship in a week what used to take a quarter. The hard part is no longer how to move quickly. It is what to point that speed at, and who to bring with you while you do." },
      { k: "pull", t: "FOMO never goes away. There is always more to learn, more to try, more being built next door. The question is not whether you feel it. It is what you do inside that feeling." },
      { k: "p", t: "I feel the fear of missing out every week. A new model drops, a framework trends, a competitor ships. That feeling is not a problem to solve. It is the weather. What matters is whether I react to it — reflexively, reaching for whatever is loudest — or whether I notice it, name it, and still choose." },
      { k: "h2", t: "Presence is how you care about people at speed" },
      { k: "p", t: "Shipping fast creates a shockwave behind you. Someone on your team is learning the tool you already mastered. Someone on the support side is answering for the change you made this morning. Someone who loved the old behavior is, quietly, feeling left behind." },
      { k: "p", t: "You do not slow down to take care of those people. You stay present to them. You write the changelog with a real human in mind. You pair for an hour with the teammate who is one version behind. You answer the question in public chat, not DMs. You make speed legible to the people it affects." },
      { k: "ol", items: [
        "Ship the change today. Do not sandbag to make it easier on yourself.",
        "Write the one-paragraph explanation before you close the PR. Not after.",
        "Notice who the change is hardest on. Tell them you noticed.",
        "Ask the person who was learning the old way what would help now. Do the thing they said."
      ]},
      { k: "h2", t: "Intention, at velocity" },
      { k: "p", t: "Mindful engineering, the way I mean it, is moving as fast as you can while staying honest about three questions. Why this, not the other thing you could have done. Who is along for the ride. What you would be proud of if someone looked at this in a year. You can ask those questions in fifteen seconds. You just have to actually ask them." },
      { k: "p", t: "Fast and present are not opposites. They are the same practice. The engineers I want to work with — and the engineer I am trying to be — move decisively, ship relentlessly, and never forget that a codebase is a thing people live inside." },
    ],
  },
  {
    id: "fomo-as-compass",
    type: "essay",
    title: "FOMO as a Compass, Not a Whip",
    subtitle: "The feeling is information. What you do with it is the practice.",
    date: "2026-03-28",
    readMin: 5,
    tags: ["practice", "change"],
    featured: true,
    excerpt: "There is too much to learn. That is the permanent condition of working in software, not a problem to outrun. But the feeling can still be useful.",
    body: [
      { k: "p", t: "There has never been a year in my career where I was not behind. Something new has always just shipped. Someone has always been using it already. This is not a problem to solve. It is the permanent condition of the job, and the sooner you stop fighting it the more you can actually learn." },
      { k: "p", t: "What changed for me was treating the fear of missing out as data. When it shows up, it is telling me something. Sometimes it is telling me there is a real shift I should chase. More often it is telling me I am lonely, or tired, or that my team has been heads-down for too long. The signal is useful. The reflex — drop everything, try the new thing, ship a demo by Friday — almost never is." },
      { k: "h2", t: "The list stays open" },
      { k: "p", t: "I keep a running list of things I have deliberately chosen not to learn this quarter. Not because they are bad. Because I am pointing my speed somewhere else right now. The list is not a moral document. It is a map of my attention, and rewriting it is one of the most honest things I do all month." },
    ],
  },
  {
    id: "left-behind",
    type: "essay",
    title: "Nobody Wants to Be the Person Left Behind",
    subtitle: "A short note to the team member who joined the wrong week.",
    date: "2026-03-14",
    readMin: 4,
    tags: ["teams", "care"],
    featured: false,
    excerpt: "Every fast team produces, as a byproduct, people who feel a version behind. Here is what I try to do about it.",
    body: [
      { k: "p", t: "Every fast team, as a byproduct of being fast, produces people who feel a version behind. You did not mean to leave them there. You were just shipping. But they are there, and pretending otherwise is its own kind of carelessness." },
    ],
  },
  {
    id: "note-compile",
    type: "note",
    date: "2026-04-15T09:14:00",
    body: "Speed without presence is just chaos with a deploy pipeline.",
  },
  {
    id: "note-meeting",
    type: "note",
    date: "2026-04-14T16:02:00",
    body: "A good changelog entry is the cheapest act of care a fast team can perform.",
  },
  {
    id: "note-garden",
    type: "note",
    date: "2026-04-11T07:40:00",
    body: "Paired for an hour today with the teammate who joined last month. They are not behind. They are arriving.",
  },
  {
    id: "note-bug",
    type: "note",
    date: "2026-04-08T22:11:00",
    body: "FOMO showed up on schedule this morning. Named it, thanked it, kept shipping the thing I had already chosen.",
  },
  {
    id: "link-craft",
    type: "link",
    date: "2026-04-10",
    title: "Worse is Better, twenty-five years on",
    source: "gabriellipman.net",
    url: "#",
    body: "The essay everyone cites and fewer have read. Worth revisiting every couple of years; what felt like contrarianism in 2000 reads like common sense now, which is itself the point.",
  },
  {
    id: "link-attention",
    type: "link",
    date: "2026-04-05",
    title: "The Attention Economy is a Debt",
    source: "new.public",
    url: "#",
    body: "A piece on notifications as borrowed time. The framing — that every push notification is a loan against your future focus — has stuck with me for weeks.",
  },
  {
    id: "snippet-retry",
    type: "snippet",
    title: "Retry with jitter, honestly",
    date: "2026-04-07",
    language: "python",
    code: `def retry(fn, attempts=5, base=0.25):\n    for i in range(attempts):\n        try:\n            return fn()\n        except Retryable as e:\n            if i == attempts - 1:\n                raise\n            sleep(base * (2 ** i) + random() * base)`,
    body: "The version I actually ship. Exponential backoff, full jitter, one line of randomness. Everything else is a configuration option I did not need.",
  },
  {
    id: "snippet-git",
    type: "snippet",
    title: "The only git alias I have kept",
    date: "2026-03-30",
    language: "bash",
    code: `# ~/.gitconfig\n[alias]\n    graph = log --oneline --graph --decorate --all`,
    body: "Everything else I've tried — elaborate prompts, custom scripts — I've abandoned within a month. This one has survived three laptops.",
  },
];

window.NOW = {
  updated: "2026-04-16",
  location: "Lisbon, Portugal",
  reading: [
    { title: "The Art of Doing Science and Engineering", author: "Hamming" },
    { title: "A Pattern Language", author: "Alexander et al." },
  ],
  working: "Shipping a new internal tool every week, and being honest about which ones stick.",
  learning: "Rust, properly this time. Also: how to give feedback faster without being careless.",
  listening: "Mostly Arvo Pärt. Some Nils Frahm. Podcasts at 1.6x.",
};
